2024-06-29 12:42:52,551 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2024-06-29 12:42:52,551 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from /opt/homebrew/lib/python3.11/site-packages/instabot/bot/bot.py
2024-06-29 12:42:56,087 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2024-06-29 12:43:56,112 - instabot version: 0.117.0 (api) - WARNING - HTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/get_prefill_candidates/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x105ec3510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
